### ISSUE TITLE
"Go to" link behaves in unexpected way

### ISSUE THREAD

**Issue by apman** [scruffian/javascripture#12]
If you click on the "Go to" field in the top left corner, anywhere except on the book symbol, the text jumps to the previous chapter. I would expect this to be either a part of the button that opens the "Go to" dialog or a non-clickable heading for the column underneath.

In Firefox the behaviour also creates an inconsistency, as it jumps back to a few pixels _above_ the heading of the previous chapter (other chapter links usually jump to verse 1), which causes the chapter selection input field at the top to display the chapter _before_ the one now visible in the main reading area.

The whole button should probably stay in place rather than scrolling out of sight when the user scrolls the chapter navigation. 

Having said all that, maybe the whole "Go to" link and dialog are redundant! Since you have two other (and probably faster) mechanisms to pick a chapter, perhaps the space at the top left would be better used to add an NT/OT toggle that quickly scrolls the appropriate chapters of the left hand chapter navigation into view.

**Comment by scruffian** [comment]
I addressed most of these issues. Still not totally happy with that section.

The dropdown lists are useful for some devices that the other interfaces don't work on yet. I like the OT/NT idea...

**Comment by scruffian** [comment]
I don't think this is an issue any more.
