### ISSUE TITLE
Strict search doesn't behave as expected

### ISSUE THREAD

**Issue by apman** [scruffian/javascripture#13]
Search returns any occurance of the search string, which in many cases is useful, but turning on Strict Search in the Settings doesn't seem to change it:

Example: Search for "ice" returns "voice", "artificer" etc. 

(I also noticed that a leading or trailing space gets ignored, but using both returns no results at all, i.e. " ice" or "ice " = "ice", but " ice " not found.)

**Comment by scruffian** [comment]
This should now be fixed.
