### ISSUE TITLE
Strict Search checkbox

### ISSUE THREAD

**Issue by apman** [scruffian/javascripture#14]
In version 4 actually the Strict Search checkbox is not working at all (not disabled, but not accepting checkmark ...?).

Maybe there should be a rollover or subtext to explain in what way it's stricter?

If it's meant to switch between searching for sub-strings and whole words it would also be better to place it into the advanced search options, because you'd want to change that on a per-search basis (unlike the search speed)

**Comment by scruffian** [comment]
I added a title to explain what this means, and also fixed it and added it to the advanced search settings. I also fixed the strict search.
