### ISSUE TITLE
Hiding original not working properly

### ISSUE THREAD

**Issue by apman** [scruffian/javascripture#3]
When I uncheck "Show original" in the Settings, only the Hebrew text disappears. Greek is shown in line with the English. And in both cases the verse numbering remains in the center, instead of appearing to the left of the text.

**Comment by scruffian** [comment]
This option was made obsolete by the full screen button. This option was removed in <a href="c5852a40513144de9ef3e52dbf5efff97e0fd611">this commit</a>
