### ISSUE TITLE
Various issues with Keyboard shortcuts

### ISSUE THREAD

**Issue by apman** [scruffian/javascripture#6]
Shortcut tips in Help and under Settings should be consolidated under Help.

Not working in either Chrome or Firefox (Win7)
- advancing through chapters with left/right curser keys
- next/prev reference with n/p

Not working in Firefox (Win7)
- next/prev reference with -/=

**Comment by scruffian** [comment]
The first set of shortcuts are old. I removed them in <a href="https://github.com/scruffian/Javascripture/commit/b8f2aaa4c74f4b2cdd4bc0f3022b9e928732eda8">this commit</a>

**Comment by scruffian** [comment]
The other shortcuts were fixed for firefox in <a href="https://github.com/scruffian/Javascripture/commit/2b356c9dea2b0ec42a5976607be141ec1c9ae16b">this commit</a>
