### ISSUE TITLE
New feature: English transliterations

### ISSUE THREAD

**Issue by apman** [scruffian/javascripture#7]
It would be nice if the word info could include an English transliteration 
(however inadequat they may be (?), for those who can't read Hebrew they still provide a useful mental handle - and it's certainly easier to discuss 'ruach' and 'neshama' than having to constantly refer to 5397 vs 7307 or the blue vs the pink spirit ;-) ... )

**Comment by scruffian** [comment]
Interesting idea. Would you expect to see this instead of the original text?

With the hebrew a transliteration would have to be very basic, as there are no vowels, but that could still be useful.

**Comment by apman** [comment]
No, I just meant in the details panel at the bottom, where you have  
  <Strongs number> | English translation | Hebrew
make it 
  <Strongs number> | English translation | Hebrew | transliteration

My Young's concordance gives a transliteration for each Hebrew and Greek word (with vowels that in the case of Hebrew presumably reflect how it's thought to have been pronounced).

**Comment by scruffian** [comment]
I added this for the hebrew text in <a href="https://github.com/scruffian/Javascripture/commit/712b632455643df29ee5a187dbf5355f63f7a735">this commit</a>

The data for the Greek isn't so easily available, but I'll look for it...

**Comment by scruffian** [comment]
I added the Greek transliterations too. Took a while!
