### ISSUE TITLE
Layout: Info pane could do with a little bit more padding

### ISSUE THREAD

**Issue by apman** [scruffian/javascripture#9]
You probably want to maximize the use of the screen estate for content, but I think a tad more padding would make the overall impression a lot more pleasing

**Comment by scruffian** [comment]
This probably needs more work, but it's certainly better like this :)

**Comment by apman** [comment]
Yep, much better!  (Maybe adding a box shadow to the top of the info pane would make the line where the Bible text disappears underneath it a little easier on the eye ... - low priority though :-)
